### ISSUE TITLE
블로그+연동+요청

### ISSUE THREAD

**Issue by younggyolee** [roketto-dan/vaco-feeds#2]
- 올려주신 블로그 글들과 자동으로 연동되고, 새로 글을 올리실 때마다 맞춰서 연동 될 예정입니다. 부트캠프를 진행하시는 분들, 그리고 수료생 분들이 보실 수 있습니다.
- 이슈가 생성되면 블로그 확인 후, 바코 피즈로 업로드 할 예정입니다.
- 별도로 궁금한 점이나 문의사항이 있다면, 바닐라코딩 슬랙에서 [저에게](https://vanillacoding.slack.com/team/U038SRXJ84V) DM 남겨주시면 감사하겠습니다.

### 올리고 싶은 블로그 주소, 혹은 블로그의 RSS Feed 링크를 남겨주세요

[블로그 주소 또는 RSS Feed 링크]

https://medium.com/@younggyo.lee./

### 간단하게 이름과 바닐라코딩 기수를 적어 주세요(바코인 확인을 위함입니다).

[N기 김바코]

7기 이영교

**Comment by 0jaaack** [comment]
안녕하세요 영교님! 바코 블로그에 연동 신청을 해주셔서 감사합니다. 

올려주신 글은 다른 바코분들한테도 많은 도움이 될 것 같습니다..! 저도 저 글을 보면서 알고리즘에 대한 의지를 키웠었던 기억이 있네요..

신청해주신 블로그는 잘 연동되었습니다! [vaco.blog](https://vaco.blog/) 감사합니다~~
