### ISSUE TITLE
블로그 연동 요청

### ISSUE THREAD

**Issue by howyoujini** [roketto-dan/vaco-feeds#4]
- 올려주신 블로그 글들과 자동으로 연동되고, 새로 글을 올리실 때마다 맞춰서 연동 될 예정입니다. 부트캠프를 진행하시는 분들, 그리고 수료생 분들이 보실 수 있습니다.
- 이슈가 생성되면 블로그 확인 후, 바코 피즈로 업로드 할 예정입니다.
- 별도로 궁금한 점이나 문의사항이 있다면, 바닐라코딩 슬랙에서 [저에게](https://vanillacoding.slack.com/team/U038SRXJ84V) DM 남겨주시면 감사하겠습니다.

### 올리고 싶은 블로그 주소, 혹은 블로그의 RSS Feed 링크를 남겨주세요

https://medium.com/@howyoujini/react-%EB%AC%B4%ED%95%9C-%EB%A0%8C%EB%8D%94%EB%A7%81-%EC%84%9C%EB%B0%94%EC%9D%B4%EB%B2%8C-2f702176fd98

### 간단하게 이름과 바닐라코딩 기수를 적어 주세요(바코인 확인을 위함입니다).

프론트 2기 홍유진

**Comment by 0jaaack** [comment]
안녕하세요 유진님, 공재혁입니다. 오랜만에 뵙네요!

올려주신 블로그 주소로 연동되도록 해두었습니다~ 부트캠프하시면서 글도 쓰기 쉽지 않으실텐데 알찬 글 쓰고 계셨었군요..!

앞으로도 응원하겠습니다~
