### ISSUE TITLE
블로그 연동 요청

### ISSUE THREAD

**Issue by SsongQ-92** [roketto-dan/vaco-feeds#5]
- 올려주신 블로그 글들과 자동으로 연동되고, 새로 글을 올리실 때마다 맞춰서 연동 될 예정입니다. 부트캠프를 진행하시는 분들, 그리고 수료생 분들이 보실 수 있습니다.
- 이슈가 생성되면 블로그 확인 후, 바코 피즈로 업로드 할 예정입니다.
- 별도로 궁금한 점이나 문의사항이 있다면, 바닐라코딩 슬랙에서 [저에게](https://vanillacoding.slack.com/team/U038SRXJ84V) DM 남겨주시면 감사하겠습니다.

### 올리고 싶은 블로그 주소, 혹은 블로그의 RSS Feed 링크를 남겨주세요

[쏭큐의 개발 블로그](https://ssongq.com/blog/deep_dive/what_is_rendering_in_react)

### 간단하게 이름과 바닐라코딩 기수를 적어 주세요(바코인 확인을 위함입니다).

<b>FE 2기 송규경</b>

첫 글의 경우, 의미 없는 글이라서, 빼고 연동이 가능하시다면 연동해주시면 감사하겠습니다.

**Comment by 0jaaack** [comment]
안녕하세요 규경님..! 공재혁입니다. 과제하시랴 플젝하시랴 바쁘실텐데 이렇게 블로그까지 만드셨었군요..!!

지금 블로그로는 연동이 안되는 상태에요. 바코 블로그는 rss 피드가 연동되어 있어야합니다..! ([예시](https://www.jaaack.dev/rss.xml)).

제가 구석구석 살펴봤는데 rss 페이지는 어디있는지 모르겠네용 ㅎㅎ;

sitemap 만드셨던것처럼 rss feed 페이지 만들어주시고 여기에 코멘트 남겨주시면 연동하겠습니다. 안되시는 부분 있으면 DM이나 코멘트 남겨주세요!

**Comment by 0jaaack** [comment]
연동 완료..

**Comment by SsongQ-92** [comment]
감사합니다 :)
