### ISSUE TITLE
블로그 연동 요청

### ISSUE THREAD

**Issue by whoisrey** [roketto-dan/vaco-feeds#6]
- 올려주신 블로그 글들과 자동으로 연동되고, 새로 글을 올리실 때마다 맞춰서 연동 될 예정입니다. 부트캠프를 진행하시는 분들, 그리고 수료생 분들이 보실 수 있습니다.
- 이슈가 생성되면 블로그 확인 후, 바코 피즈로 업로드 할 예정입니다.
- 별도로 궁금한 점이나 문의사항이 있다면, 바닐라코딩 슬랙에서 [저에게](https://vanillacoding.slack.com/team/U038SRXJ84V) DM 남겨주시면 감사하겠습니다.

### 올리고 싶은 블로그 주소, 혹은 블로그의 RSS Feed 링크를 남겨주세요

https://devrey.blog

### 간단하게 이름과 바닐라코딩 기수를 적어 주세요(바코인 확인을 위함입니다).

[17기 이양래]

재혁님 감사합니다.

**Comment by 0jaaack** [comment]
안녕하세요 양래님! 블로그 연동 신청해주셔서 감사합니다...!

블로그에 RSS feed 연동이 되어있지 않은 상태로 보여요. https://devrey.blog/rss.xml 으로 접속해봤는데 404가 뜨네요..
블로그 레포를 보니까 엔드포인트는 만들어져있는데, 배포가 안된 걸까요..? 

다시 RSS 페이지가 있는건지 확인해주시고 코멘트 남겨주시면 반영하겠습니다~

**Comment by whoisrey** [comment]
안녕하세요, 재혁님!

RSS 피드를 연동하지 않은 상태로 신청하여 문제가 발생했던 것 같습니다.
다시 한 번 확인 가능하실까요?

https://devrey.blog/rss.xml

바쁘실텐데 번거롭게 해드려 죄송합니다..!

**Comment by oddmj** [comment]
추가됐습니다 감사합니다 🙏
