### ISSUE TITLE
블로그 연동 요청

### ISSUE THREAD

**Issue by coco8j** [roketto-dan/vaco-feeds#7]
- 올려주신 블로그 글들과 자동으로 연동되고, 새로 글을 올리실 때마다 맞춰서 연동 될 예정입니다. 부트캠프를 진행하시는 분들, 그리고 수료생 분들이 보실 수 있습니다.
- 이슈가 생성되면 블로그 확인 후, 바코 피즈로 업로드 할 예정입니다.
- 별도로 궁금한 점이나 문의사항이 있다면, 바닐라코딩 슬랙에서 [저에게](https://vanillacoding.slack.com/team/U038SRXJ84V) DM 남겨주시면 감사하겠습니다.

### 올리고 싶은 블로그 주소, 혹은 블로그의 RSS Feed 링크를 남겨주세요

https://www.coco-study.site/

### 간단하게 이름과 바닐라코딩 기수를 적어 주세요(바코인 확인을 위함입니다).

[풀스택 17기 이주연]

뽀짝하지만 신청합니다.

**Comment by 0jaaack** [comment]
안녕하세요 주연님! 드디어 신청해주셨군요..

그런데 하나 문제가 있는데요.. rss feed 엔드포인트는 잘 연결되어있는데, rss 피드 내에 site 주소가 잘못 설정된 것 같아요...! 

site 주소가 `example.me`라고 설정되어있어서 연동해도 정보를 가져올 수가 없는데, 확인해주시면 감사하겠습니다!

<img width="499" alt="Screenshot 2024-12-07 at 3 19 48 PM" src="https://github.com/user-attachments/assets/ba9c33cc-a21e-4f26-8576-c1a60e28a912">

**Comment by coco8j** [comment]
@0jaaack  수정했습니다..! 중간에 템플릿으로 갈아탔는데 설정이 미처 다 안끝난 곳이 있었네요 ㅜㅜㅎ 감사합니다!

**Comment by 0jaaack** [comment]
연동 완료..
